@echo off
set "GIT_PATH=C:\Program Files\Git\cmd\git.exe"
echo Initializing Git...
"%GIT_PATH%" init
echo Adding remote origin...
"%GIT_PATH%" remote add origin https://github.com/hyuny86/scheduler
echo Committing files...
"%GIT_PATH%" add .
"%GIT_PATH%" commit -m "Initial commit: Flask Schedule Planner with Admin/Viewer modes"
echo Pushing to GitHub...
"%GIT_PATH%" push -u origin main
pause
